export interface CountryCodeData {
    key: string;       // ISO 3166-1 alpha-2 code (lowercase)
    label: string;     // Full country name
    flag: string;      // Emoji flag
    code: string;      // International dialing code
    maxLength: number; // Maximum phone number length (estimate/international format without code)
}

export const countryCodes: CountryCodeData[] = [
    { key: 'af', label: 'Afghanistan', flag: '🇦🇫', code: '+93', maxLength: 9 },
    { key: 'al', label: 'Albania', flag: '🇦🇱', code: '+355', maxLength: 9 },
    { key: 'dz', label: 'Algeria', flag: '🇩🇿', code: '+213', maxLength: 9 },
    { key: 'as', label: 'American Samoa', flag: '🇦🇸', code: '+1-684', maxLength: 7 },
    { key: 'ad', label: 'Andorra', flag: '🇦🇩', code: '+376', maxLength: 6 },
    { key: 'ao', label: 'Angola', flag: '🇦🇴', code: '+244', maxLength: 9 },
    { key: 'ai', label: 'Anguilla', flag: '🇦🇮', code: '+1-264', maxLength: 7 },
    { key: 'ag', label: 'Antigua and Barbuda', flag: '🇦🇬', code: '+1-268', maxLength: 7 },
    { key: 'ar', label: 'Argentina', flag: '🇦🇷', code: '+54', maxLength: 10 },
    { key: 'am', label: 'Armenia', flag: '🇦🇲', code: '+374', maxLength: 8 },
    { key: 'aw', label: 'Aruba', flag: '🇦🇼', code: '+297', maxLength: 7 },
    { key: 'au', label: 'Australia', flag: '🇦🇺', code: '+61', maxLength: 9 },
    { key: 'at', label: 'Austria', flag: '🇦🇹', code: '+43', maxLength: 10 },
    { key: 'az', label: 'Azerbaijan', flag: '🇦🇿', code: '+994', maxLength: 9 },
    { key: 'bs', label: 'Bahamas', flag: '🇧🇸', code: '+1-242', maxLength: 7 },
    { key: 'bh', label: 'Bahrain', flag: '🇧🇭', code: '+973', maxLength: 8 },
    { key: 'bd', label: 'Bangladesh', flag: '🇧🇩', code: '+880', maxLength: 10 },
    { key: 'bb', label: 'Barbados', flag: '🇧🇧', code: '+1-246', maxLength: 7 },
    { key: 'by', label: 'Belarus', flag: '🇧🇾', code: '+375', maxLength: 9 },
    { key: 'be', label: 'Belgium', flag: '🇧🇪', code: '+32', maxLength: 9 },
    { key: 'bz', label: 'Belize', flag: '🇧🇿', code: '+501', maxLength: 7 },
    { key: 'bj', label: 'Benin', flag: '🇧🇯', code: '+229', maxLength: 8 },
    { key: 'bm', label: 'Bermuda', flag: '🇧🇲', code: '+1-441', maxLength: 7 },
    { key: 'bt', label: 'Bhutan', flag: '🇧🇹', code: '+975', maxLength: 8 },
    { key: 'bo', label: 'Bolivia', flag: '🇧🇴', code: '+591', maxLength: 8 },
    { key: 'ba', label: 'Bosnia and Herzegovina', flag: '🇧🇦', code: '+387', maxLength: 8 },
    { key: 'bw', label: 'Botswana', flag: '🇧🇼', code: '+267', maxLength: 7 },
    { key: 'br', label: 'Brazil', flag: '🇧🇷', code: '+55', maxLength: 11 },
    { key: 'io', label: 'British Indian Ocean Territory', flag: '🇮🇴', code: '+246', maxLength: 7 },
    { key: 'vg', label: 'British Virgin Islands', flag: '🇻🇬', code: '+1-284', maxLength: 7 },
    { key: 'bn', label: 'Brunei', flag: '🇧🇳', code: '+673', maxLength: 7 },
    { key: 'bg', label: 'Bulgaria', flag: '🇧🇬', code: '+359', maxLength: 9 },
    { key: 'bf', label: 'Burkina Faso', flag: '🇧🇫', code: '+226', maxLength: 8 },
    { key: 'bi', label: 'Burundi', flag: '🇧🇮', code: '+257', maxLength: 8 },
    { key: 'kh', label: 'Cambodia', flag: '🇰🇭', code: '+855', maxLength: 9 },
    { key: 'cm', label: 'Cameroon', flag: '🇨🇲', code: '+237', maxLength: 9 },
    { key: 'ca', label: 'Canada', flag: '🇨🇦', code: '+1', maxLength: 10 },
    { key: 'cv', label: 'Cape Verde', flag: '🇨🇻', code: '+238', maxLength: 7 },
    { key: 'ky', label: 'Cayman Islands', flag: '🇰🇾', code: '+1-345', maxLength: 7 },
    { key: 'cf', label: 'Central African Republic', flag: '🇨🇫', code: '+236', maxLength: 8 },
    { key: 'td', label: 'Chad', flag: '🇹🇩', code: '+235', maxLength: 8 },
    { key: 'cl', label: 'Chile', flag: '🇨🇱', code: '+56', maxLength: 9 },
    { key: 'cn', label: 'China', flag: '🇨🇳', code: '+86', maxLength: 11 },
    { key: 'cx', label: 'Christmas Island', flag: '🇨🇽', code: '+61', maxLength: 9 },
    { key: 'cc', label: 'Cocos Islands', flag: '🇨🇨', code: '+61', maxLength: 9 },
    { key: 'co', label: 'Colombia', flag: '🇨🇴', code: '+57', maxLength: 10 },
    { key: 'km', label: 'Comoros', flag: '🇰🇲', code: '+269', maxLength: 7 },
    { key: 'ck', label: 'Cook Islands', flag: '🇨🇰', code: '+682', maxLength: 5 },
    { key: 'cr', label: 'Costa Rica', flag: '🇨🇷', code: '+506', maxLength: 8 },
    { key: 'hr', label: 'Croatia', flag: '🇭🇷', code: '+385', maxLength: 9 },
    { key: 'cu', label: 'Cuba', flag: '🇨🇺', code: '+53', maxLength: 8 },
    { key: 'cw', label: 'Curaçao', flag: '🇨🇼', code: '+599', maxLength: 7 },
    { key: 'cy', label: 'Cyprus', flag: '🇨🇾', code: '+357', maxLength: 8 },
    { key: 'cz', label: 'Czech Republic', flag: '🇨🇿', code: '+420', maxLength: 9 },
    { key: 'cd', label: 'Democratic Republic of the Congo', flag: '🇨🇩', code: '+243', maxLength: 9 },
    { key: 'dk', label: 'Denmark', flag: '🇩🇰', code: '+45', maxLength: 8 },
    { key: 'dj', label: 'Djibouti', flag: '🇩🇯', code: '+253', maxLength: 8 },
    { key: 'dm', label: 'Dominica', flag: '🇩🇲', code: '+1-767', maxLength: 7 },
    { key: 'do', label: 'Dominican Republic', flag: '🇩🇴', code: '+1-809', maxLength: 7 },
    { key: 'ec', label: 'Ecuador', flag: '🇪🇨', code: '+593', maxLength: 9 },
    { key: 'eg', label: 'Egypt', flag: '🇪🇬', code: '+20', maxLength: 10 },
    { key: 'sv', label: 'El Salvador', flag: '🇸🇻', code: '+503', maxLength: 8 },
    { key: 'gq', label: 'Equatorial Guinea', flag: '🇬🇶', code: '+240', maxLength: 9 },
    { key: 'er', label: 'Eritrea', flag: '🇪🇷', code: '+291', maxLength: 7 },
    { key: 'ee', label: 'Estonia', flag: '🇪🇪', code: '+372', maxLength: 7 },
    { key: 'et', label: 'Ethiopia', flag: '🇪🇹', code: '+251', maxLength: 9 },
    { key: 'fk', label: 'Falkland Islands', flag: '🇫🇰', code: '+500', maxLength: 5 },
    { key: 'fo', label: 'Faroe Islands', flag: '🇫🇴', code: '+298', maxLength: 6 },
    { key: 'fj', label: 'Fiji', flag: '🇫🇯', code: '+679', maxLength: 7 },
    { key: 'fi', label: 'Finland', flag: '🇫🇮', code: '+358', maxLength: 9 },
    { key: 'fr', label: 'France', flag: '🇫🇷', code: '+33', maxLength: 9 },
    { key: 'gf', label: 'French Guiana', flag: '🇬🇫', code: '+594', maxLength: 9 },
    { key: 'pf', label: 'French Polynesia', flag: '🇵🇫', code: '+689', maxLength: 6 },
    { key: 'ga', label: 'Gabon', flag: '🇬🇦', code: '+241', maxLength: 8 },
    { key: 'gm', label: 'Gambia', flag: '🇬🇲', code: '+220', maxLength: 7 },
    { key: 'ge', label: 'Georgia', flag: '🇬🇪', code: '+995', maxLength: 9 },
    { key: 'de', label: 'Germany', flag: '🇩🇪', code: '+49', maxLength: 11 },
    { key: 'gh', label: 'Ghana', flag: '🇬🇭', code: '+233', maxLength: 9 },
    { key: 'gi', label: 'Gibraltar', flag: '🇬🇮', code: '+350', maxLength: 8 },
    { key: 'gr', label: 'Greece', flag: '🇬🇷', code: '+30', maxLength: 10 },
    { key: 'gl', label: 'Greenland', flag: '🇬🇱', code: '+299', maxLength: 6 },
    { key: 'gd', label: 'Grenada', flag: '🇬🇩', code: '+1-473', maxLength: 7 },
    { key: 'gp', label: 'Guadeloupe', flag: '🇬🇵', code: '+590', maxLength: 9 },
    { key: 'gu', label: 'Guam', flag: '🇬🇺', code: '+1-671', maxLength: 7 },
    { key: 'gt', label: 'Guatemala', flag: '🇬🇹', code: '+502', maxLength: 8 },
    { key: 'gg', label: 'Guernsey', flag: '🇬🇬', code: '+44-1481', maxLength: 10 },
    { key: 'gn', label: 'Guinea', flag: '🇬🇳', code: '+224', maxLength: 8 },
    { key: 'gw', label: 'Guinea-Bissau', flag: '🇬🇼', code: '+245', maxLength: 7 },
    { key: 'gy', label: 'Guyana', flag: '🇬🇾', code: '+592', maxLength: 7 },
    { key: 'ht', label: 'Haiti', flag: '🇭🇹', code: '+509', maxLength: 8 },
    { key: 'hn', label: 'Honduras', flag: '🇭🇳', code: '+504', maxLength: 8 },
    { key: 'hk', label: 'Hong Kong', flag: '🇭🇰', code: '+852', maxLength: 8 },
    { key: 'hu', label: 'Hungary', flag: '🇭🇺', code: '+36', maxLength: 9 },
    { key: 'is', label: 'Iceland', flag: '🇮🇸', code: '+354', maxLength: 7 },
    { key: 'in', label: 'India', flag: '🇮🇳', code: '+91', maxLength: 10 },
    { key: 'id', label: 'Indonesia', flag: '🇮🇩', code: '+62', maxLength: 11 },
    { key: 'ir', label: 'Iran', flag: '🇮🇷', code: '+98', maxLength: 10 },
    { key: 'iq', label: 'Iraq', flag: '🇮🇶', code: '+964', maxLength: 10 },
    { key: 'ie', label: 'Ireland', flag: '🇮🇪', code: '+353', maxLength: 9 },
    { key: 'im', label: 'Isle of Man', flag: '🇮🇲', code: '+44-1624', maxLength: 10 },
    { key: 'it', label: 'Italy', flag: '🇮🇹', code: '+39', maxLength: 10 },
    { key: 'ci', label: 'Ivory Coast', flag: '🇨🇮', code: '+225', maxLength: 8 },
    { key: 'jm', label: 'Jamaica', flag: '🇯🇲', code: '+1-876', maxLength: 7 },
    { key: 'jp', label: 'Japan', flag: '🇯🇵', code: '+81', maxLength: 10 },
    { key: 'je', label: 'Jersey', flag: '🇯🇪', code: '+44-1534', maxLength: 10 },
    { key: 'jo', label: 'Jordan', flag: '🇯🇴', code: '+962', maxLength: 8 },
    { key: 'kz', label: 'Kazakhstan', flag: '🇰🇿', code: '+7', maxLength: 10 },
    { key: 'ke', label: 'Kenya', flag: '🇰🇪', code: '+254', maxLength: 9 },
    { key: 'ki', label: 'Kiribati', flag: '🇰🇮', code: '+686', maxLength: 8 },
    { key: 'xk', label: 'Kosovo', flag: '🇽🇰', code: '+383', maxLength: 8 },
    { key: 'kw', label: 'Kuwait', flag: '🇰🇼', code: '+965', maxLength: 8 },
    { key: 'kg', label: 'Kyrgyzstan', flag: '🇰🇬', code: '+996', maxLength: 9 },
    { key: 'la', label: 'Laos', flag: '🇱🇦', code: '+856', maxLength: 9 },
    { key: 'lv', label: 'Latvia', flag: '🇱🇻', code: '+371', maxLength: 8 },
    { key: 'lb', label: 'Lebanon', flag: '🇱🇧', code: '+961', maxLength: 8 },
    { key: 'ls', label: 'Lesotho', flag: '🇱🇸', code: '+266', maxLength: 8 },
    { key: 'lr', label: 'Liberia', flag: '🇱🇷', code: '+231', maxLength: 8 },
    { key: 'ly', label: 'Libya', flag: '🇱🇾', code: '+218', maxLength: 9 },
    { key: 'li', label: 'Liechtenstein', flag: '🇱🇮', code: '+423', maxLength: 7 },
    { key: 'lt', label: 'Lithuania', flag: '🇱🇹', code: '+370', maxLength: 8 },
    { key: 'lu', label: 'Luxembourg', flag: '🇱🇺', code: '+352', maxLength: 9 },
    { key: 'mo', label: 'Macau', flag: '🇲🇴', code: '+853', maxLength: 8 },
    { key: 'mk', label: 'North Macedonia', flag: '🇲🇰', code: '+389', maxLength: 8 },
    { key: 'mg', label: 'Madagascar', flag: '🇲🇬', code: '+261', maxLength: 9 },
    { key: 'mw', label: 'Malawi', flag: '🇲🇼', code: '+265', maxLength: 8 },
    { key: 'my', label: 'Malaysia', flag: '🇲🇾', code: '+60', maxLength: 9 },
    { key: 'mv', label: 'Maldives', flag: '🇲🇻', code: '+960', maxLength: 7 },
    { key: 'ml', label: 'Mali', flag: '🇲🇱', code: '+223', maxLength: 8 },
    { key: 'mt', label: 'Malta', flag: '🇲🇹', code: '+356', maxLength: 8 },
    { key: 'mh', label: 'Marshall Islands', flag: '🇲🇭', code: '+692', maxLength: 7 },
    { key: 'mq', label: 'Martinique', flag: '🇲🇶', code: '+596', maxLength: 9 },
    { key: 'mr', label: 'Mauritania', flag: '🇲🇷', code: '+222', maxLength: 8 },
    { key: 'mu', label: 'Mauritius', flag: '🇲🇺', code: '+230', maxLength: 7 },
    { key: 'yt', label: 'Mayotte', flag: '🇾🇹', code: '+262', maxLength: 9 },
    { key: 'mx', label: 'Mexico', flag: '🇲🇽', code: '+52', maxLength: 10 },
    { key: 'fm', label: 'Micronesia', flag: '🇫🇲', code: '+691', maxLength: 7 },
    { key: 'md', label: 'Moldova', flag: '🇲🇩', code: '+373', maxLength: 8 },
    { key: 'mc', label: 'Monaco', flag: '🇲🇨', code: '+377', maxLength: 8 },
    { key: 'mn', label: 'Mongolia', flag: '🇲🇳', code: '+976', maxLength: 8 },
    { key: 'me', label: 'Montenegro', flag: '🇲🇪', code: '+382', maxLength: 8 },
    { key: 'ms', label: 'Montserrat', flag: '🇲🇸', code: '+1-664', maxLength: 7 },
    { key: 'ma', label: 'Morocco', flag: '🇲🇦', code: '+212', maxLength: 9 },
    { key: 'mz', label: 'Mozambique', flag: '🇲🇿', code: '+258', maxLength: 9 },
    { key: 'mm', label: 'Myanmar', flag: '🇲🇲', code: '+95', maxLength: 9 },
    { key: 'na', label: 'Namibia', flag: '🇳🇦', code: '+264', maxLength: 9 },
    { key: 'nr', label: 'Nauru', flag: '🇳🇷', code: '+674', maxLength: 7 },
    { key: 'np', label: 'Nepal', flag: '🇳🇵', code: '+977', maxLength: 10 },
    { key: 'nl', label: 'Netherlands', flag: '🇳🇱', code: '+31', maxLength: 9 },
    { key: 'nc', label: 'New Caledonia', flag: '🇳🇨', code: '+687', maxLength: 6 },
    { key: 'nz', label: 'New Zealand', flag: '🇳🇿', code: '+64', maxLength: 9 },
    { key: 'ni', label: 'Nicaragua', flag: '🇳🇮', code: '+505', maxLength: 8 },
    { key: 'ne', label: 'Niger', flag: '🇳🇪', code: '+227', maxLength: 8 },
    { key: 'ng', label: 'Nigeria', flag: '🇳🇬', code: '+234', maxLength: 10 },
    { key: 'nu', label: 'Niue', flag: '🇳🇺', code: '+683', maxLength: 4 },
    { key: 'nf', label: 'Norfolk Island', flag: '🇳🇫', code: '+672', maxLength: 6 },
    { key: 'kp', label: 'North Korea', flag: '🇰🇵', code: '+850', maxLength: 8 },
    { key: 'mp', label: 'Northern Mariana Islands', flag: '🇲🇵', code: '+1-670', maxLength: 7 },
    { key: 'no', label: 'Norway', flag: '🇳🇴', code: '+47', maxLength: 8 },
    { key: 'om', label: 'Oman', flag: '🇴🇲', code: '+968', maxLength: 8 },
    { key: 'pk', label: 'Pakistan', flag: '🇵🇰', code: '+92', maxLength: 10 },
    { key: 'pw', label: 'Palau', flag: '🇵🇼', code: '+680', maxLength: 7 },
    { key: 'ps', label: 'Palestine', flag: '🇵🇸', code: '+970', maxLength: 9 },
    { key: 'pa', label: 'Panama', flag: '🇵🇦', code: '+507', maxLength: 8 },
    { key: 'pg', label: 'Papua New Guinea', flag: '🇵🇬', code: '+675', maxLength: 8 },
    { key: 'py', label: 'Paraguay', flag: '🇵🇾', code: '+595', maxLength: 9 },
    { key: 'pe', label: 'Peru', flag: '🇵🇪', code: '+51', maxLength: 9 },
    { key: 'ph', label: 'Philippines', flag: '🇵🇭', code: '+63', maxLength: 10 },
    { key: 'pl', label: 'Poland', flag: '🇵🇱', code: '+48', maxLength: 9 },
    { key: 'pt', label: 'Portugal', flag: '🇵🇹', code: '+351', maxLength: 9 },
    { key: 'pr', label: 'Puerto Rico', flag: '🇵🇷', code: '+1-787', maxLength: 7 },
    { key: 'qa', label: 'Qatar', flag: '🇶🇦', code: '+974', maxLength: 8 },
    { key: 'cg', label: 'Republic of the Congo', flag: '🇨🇬', code: '+242', maxLength: 9 },
    { key: 're', label: 'Réunion', flag: '🇷🇪', code: '+262', maxLength: 9 },
    { key: 'ro', label: 'Romania', flag: '🇷🇴', code: '+40', maxLength: 9 },
    { key: 'ru', label: 'Russia', flag: '🇷🇺', code: '+7', maxLength: 10 },
    { key: 'rw', label: 'Rwanda', flag: '🇷🇼', code: '+250', maxLength: 9 },
    { key: 'bl', label: 'Saint Barthélemy', flag: '🇧🇱', code: '+590', maxLength: 9 },
    { key: 'sh', label: 'Saint Helena', flag: '🇸🇭', code: '+290', maxLength: 8 },
    { key: 'kn', label: 'Saint Kitts and Nevis', flag: '🇰🇳', code: '+1-869', maxLength: 7 },
    { key: 'lc', label: 'Saint Lucia', flag: '🇱🇨', code: '+1-758', maxLength: 7 },
    { key: 'mf', label: 'Saint Martin', flag: '🇲🇫', code: '+590', maxLength: 9 },
    { key: 'pm', label: 'Saint Pierre and Miquelon', flag: '🇵🇲', code: '+508', maxLength: 6 },
    { key: 'vc', label: 'Saint Vincent and the Grenadines', flag: '🇻🇨', code: '+1-784', maxLength: 7 },
    { key: 'ws', label: 'Samoa', flag: '🇼🇸', code: '+685', maxLength: 7 },
    { key: 'sm', label: 'San Marino', flag: '🇸🇲', code: '+378', maxLength: 7 },
    { key: 'st', label: 'São Tomé and Príncipe', flag: '🇸🇹', code: '+239', maxLength: 7 },
    { key: 'sa', label: 'Saudi Arabia', flag: '🇸🇦', code: '+966', maxLength: 9 },
    { key: 'sn', label: 'Senegal', flag: '🇸🇳', code: '+221', maxLength: 9 },
    { key: 'rs', label: 'Serbia', flag: '🇷🇸', code: '+381', maxLength: 9 },
    { key: 'sc', label: 'Seychelles', flag: '🇸🇨', code: '+248', maxLength: 7 },
    { key: 'sl', label: 'Sierra Leone', flag: '🇸🇱', code: '+232', maxLength: 8 },
    { key: 'sg', label: 'Singapore', flag: '🇸🇬', code: '+65', maxLength: 8 },
    { key: 'sx', label: 'Sint Maarten', flag: '🇸🇽', code: '+1-721', maxLength: 7 },
    { key: 'sk', label: 'Slovakia', flag: '🇸🇰', code: '+421', maxLength: 9 },
    { key: 'si', label: 'Slovenia', flag: '🇸🇮', code: '+386', maxLength: 8 },
    { key: 'sb', label: 'Solomon Islands', flag: '🇸🇧', code: '+677', maxLength: 7 },
    { key: 'so', label: 'Somalia', flag: '🇸🇴', code: '+252', maxLength: 8 },
    { key: 'za', label: 'South Africa', flag: '🇿🇦', code: '+27', maxLength: 9 },
    { key: 'kr', label: 'South Korea', flag: '🇰🇷', code: '+82', maxLength: 10 },
    { key: 'ss', label: 'South Sudan', flag: '🇸🇸', code: '+211', maxLength: 9 },
    { key: 'es', label: 'Spain', flag: '🇪🇸', code: '+34', maxLength: 9 },
    { key: 'lk', label: 'Sri Lanka', flag: '🇱🇰', code: '+94', maxLength: 9 },
    { key: 'sd', label: 'Sudan', flag: '🇸🇩', code: '+249', maxLength: 9 },
    { key: 'sr', label: 'Suriname', flag: '🇸🇷', code: '+597', maxLength: 7 },
    { key: 'sj', label: 'Svalbard and Jan Mayen', flag: '🇸🇯', code: '+47', maxLength: 8 },
    { key: 'sz', label: 'Eswatini', flag: '🇸🇿', code: '+268', maxLength: 8 },
    { key: 'se', label: 'Sweden', flag: '🇸🇪', code: '+46', maxLength: 9 },
    { key: 'ch', label: 'Switzerland', flag: '🇨🇭', code: '+41', maxLength: 9 },
    { key: 'sy', label: 'Syria', flag: '🇸🇾', code: '+963', maxLength: 8 },
    { key: 'tw', label: 'Taiwan', flag: '🇹🇼', code: '+886', maxLength: 9 },
    { key: 'tj', label: 'Tajikistan', flag: '🇹🇯', code: '+992', maxLength: 9 },
    { key: 'tz', label: 'Tanzania', flag: '🇹🇿', code: '+255', maxLength: 9 },
    { key: 'th', label: 'Thailand', flag: '🇹🇭', code: '+66', maxLength: 9 },
    { key: 'tl', label: 'Timor-Leste', flag: '🇹🇱', code: '+670', maxLength: 8 },
    { key: 'tg', label: 'Togo', flag: '🇹🇬', code: '+228', maxLength: 8 },
    { key: 'tk', label: 'Tokelau', flag: '🇹🇰', code: '+690', maxLength: 4 },
    { key: 'to', label: 'Tonga', flag: '🇹🇴', code: '+676', maxLength: 7 },
    { key: 'tt', label: 'Trinidad and Tobago', flag: '🇹🇹', code: '+1-868', maxLength: 7 },
    { key: 'tn', label: 'Tunisia', flag: '🇹🇳', code: '+216', maxLength: 8 },
    { key: 'tr', label: 'Turkey', flag: '🇹🇷', code: '+90', maxLength: 10 },
    { key: 'tm', label: 'Turkmenistan', flag: '🇹🇲', code: '+993', maxLength: 8 },
    { key: 'tc', label: 'Turks and Caicos Islands', flag: '🇹🇨', code: '+1-649', maxLength: 7 },
    { key: 'tv', label: 'Tuvalu', flag: '🇹🇻', code: '+688', maxLength: 5 },
    { key: 'vi', label: 'U.S. Virgin Islands', flag: '🇻🇮', code: '+1-340', maxLength: 7 },
    { key: 'ug', label: 'Uganda', flag: '🇺🇬', code: '+256', maxLength: 9 },
    { key: 'ua', label: 'Ukraine', flag: '🇺🇦', code: '+380', maxLength: 9 },
    { key: 'ae', label: 'United Arab Emirates', flag: '🇦🇪', code: '+971', maxLength: 9 },
    { key: 'gb', label: 'United Kingdom', flag: '🇬🇧', code: '+44', maxLength: 10 },
    { key: 'us', label: 'United States', flag: '🇺🇸', code: '+1', maxLength: 10 },
    { key: 'uy', label: 'Uruguay', flag: '🇺🇾', code: '+598', maxLength: 8 },
    { key: 'uz', label: 'Uzbekistan', flag: '🇺🇿', code: '+998', maxLength: 9 },
    { key: 'vu', label: 'Vanuatu', flag: '🇻🇺', code: '+678', maxLength: 7 },
    { key: 'va', label: 'Vatican City', flag: '🇻🇦', code: '+379', maxLength: 7 },
    { key: 've', label: 'Venezuela', flag: '🇻🇪', code: '+58', maxLength: 10 },
    { key: 'vn', label: 'Vietnam', flag: '🇻🇳', code: '+84', maxLength: 9 },
    { key: 'wf', label: 'Wallis and Futuna', flag: '🇼🇫', code: '+681', maxLength: 6 },
    { key: 'eh', label: 'Western Sahara', flag: '🇪🇭', code: '+212', maxLength: 9 },
    { key: 'ye', label: 'Yemen', flag: '🇾🇪', code: '+967', maxLength: 8 },
    { key: 'zm', label: 'Zambia', flag: '🇿🇲', code: '+260', maxLength: 9 },
    { key: 'zw', label: 'Zimbabwe', flag: '🇿🇼', code: '+263', maxLength: 9 },
];

// Helper function to get country by key
export function getCountryByKey(key: string): CountryCodeData | undefined {
    return countryCodes.find(country => country.key === key.toLowerCase());
}

// Helper function to get country by phone code
export function getCountryByCode(code: string): CountryCodeData | undefined {
    return countryCodes.find(country => country.code === code);
}

// Helper function to get country by label
export function getCountryByLabel(label: string): CountryCodeData | undefined {
    return countryCodes.find(country => country.label.toLowerCase() === label.toLowerCase());
}