export const countriesCode = [
    { key: "AF", label: "Afghanistan (+93)", value: "+93" },
    { key: "AL", label: "Albania (+355)", value: "+355" },
    { key: "DZ", label: "Algeria (+213)", value: "+213" },
    { key: "AD", label: "Andorra (+376)", value: "+376" },
    { key: "AO", label: "Angola (+244)", value: "+244" },
    { key: "AG", label: "Antigua and Barbuda (+1-268)", value: "+1-268" },
    { key: "AR", label: "Argentina (+54)", value: "+54" },
    { key: "AM", label: "Armenia (+374)", value: "+374" },
    { key: "AU", label: "Australia (+61)", value: "+61" },
    { key: "AT", label: "Austria (+43)", value: "+43" },
    { key: "AZ", label: "Azerbaijan (+994)", value: "+994" },
    { key: "BS", label: "Bahamas (+1-242)", value: "+1-242" },
    { key: "BH", label: "Bahrain (+973)", value: "+973" },
    { key: "BD", label: "Bangladesh (+880)", value: "+880" },
    { key: "BB", label: "Barbados (+1-246)", value: "+1-246" },
    { key: "BY", label: "Belarus (+375)", value: "+375" },
    { key: "BE", label: "Belgium (+32)", value: "+32" },
    { key: "BZ", label: "Belize (+501)", value: "+501" },
    { key: "BJ", label: "Benin (+229)", value: "+229" },
    { key: "BT", label: "Bhutan (+975)", value: "+975" },
    { key: "BO", label: "Bolivia (+591)", value: "+591" },
    { key: "BA", label: "Bosnia and Herzegovina (+387)", value: "+387" },
    { key: "BW", label: "Botswana (+267)", value: "+267" },
    { key: "BR", label: "Brazil (+55)", value: "+55" },
    { key: "BN", label: "Brunei (+673)", value: "+673" },
    { key: "BG", label: "Bulgaria (+359)", value: "+359" },
    { key: "BF", label: "Burkina Faso (+226)", value: "+226" },
    { key: "BI", label: "Burundi (+257)", value: "+257" },
    { key: "CV", label: "Cabo Verde (+238)", value: "+238" },
    { key: "KH", label: "Cambodia (+855)", value: "+855" },
    { key: "CM", label: "Cameroon (+237)", value: "+237" },
    { key: "CA", label: "Canada (+1)", value: "+1" },
    { key: "CF", label: "Central African Republic (+236)", value: "+236" },
    { key: "TD", label: "Chad (+235)", value: "+235" },
    { key: "CL", label: "Chile (+56)", value: "+56" },
    { key: "CN", label: "China (+86)", value: "+86" },
    { key: "CO", label: "Colombia (+57)", value: "+57" },
    { key: "KM", label: "Comoros (+269)", value: "+269" },
    { key: "CG", label: "Congo (+242)", value: "+242" },
    { key: "CD", label: "Congo, Democratic Republic (+243)", value: "+243" },
    { key: "CR", label: "Costa Rica (+506)", value: "+506" },
    { key: "CI", label: "Côte d'Ivoire (+225)", value: "+225" },
    { key: "HR", label: "Croatia (+385)", value: "+385" },
    { key: "CU", label: "Cuba (+53)", value: "+53" },
    { key: "CY", label: "Cyprus (+357)", value: "+357" },
    { key: "CZ", label: "Czech Republic (+420)", value: "+420" },
    { key: "DK", label: "Denmark (+45)", value: "+45" },
    { key: "DJ", label: "Djibouti (+253)", value: "+253" },
    { key: "DM", label: "Dominica (+1-767)", value: "+1-767" },
    { key: "DO", label: "Dominican Republic (+1-809)", value: "+1-809" },
    { key: "EC", label: "Ecuador (+593)", value: "+593" },
    { key: "EG", label: "Egypt (+20)", value: "+20" },
    { key: "SV", label: "El Salvador (+503)", value: "+503" },
    { key: "GQ", label: "Equatorial Guinea (+240)", value: "+240" },
    { key: "ER", label: "Eritrea (+291)", value: "+291" },
    { key: "EE", label: "Estonia (+372)", value: "+372" },
    { key: "SZ", label: "Eswatini (+268)", value: "+268" },
    { key: "ET", label: "Ethiopia (+251)", value: "+251" },
    { key: "FJ", label: "Fiji (+679)", value: "+679" },
    { key: "FI", label: "Finland (+358)", value: "+358" },
    { key: "FR", label: "France (+33)", value: "+33" },
    { key: "GA", label: "Gabon (+241)", value: "+241" },
    { key: "GM", label: "Gambia (+220)", value: "+220" },
    { key: "GE", label: "Georgia (+995)", value: "+995" },
    { key: "DE", label: "Germany (+49)", value: "+49" },
    { key: "GH", label: "Ghana (+233)", value: "+233" },
    { key: "GR", label: "Greece (+30)", value: "+30" },
    { key: "GD", label: "Grenada (+1-473)", value: "+1-473" },
    { key: "GT", label: "Guatemala (+502)", value: "+502" },
    { key: "GN", label: "Guinea (+224)", value: "+224" },
    { key: "GW", label: "Guinea-Bissau (+245)", value: "+245" },
    { key: "GY", label: "Guyana (+592)", value: "+592" },
    { key: "HT", label: "Haiti (+509)", value: "+509" },
    { key: "HN", label: "Honduras (+504)", value: "+504" },
    { key: "HU", label: "Hungary (+36)", value: "+36" },
    { key: "IS", label: "Iceland (+354)", value: "+354" },
    { key: "IN", label: "India (+91)", value: "+91" },
    { key: "ID", label: "Indonesia (+62)", value: "+62" },
    { key: "IR", label: "Iran (+98)", value: "+98" },
    { key: "IQ", label: "Iraq (+964)", value: "+964" },
    { key: "IE", label: "Ireland (+353)", value: "+353" },
    { key: "IT", label: "Italy (+39)", value: "+39" },
    { key: "JM", label: "Jamaica (+1-876)", value: "+1-876" },
    { key: "JP", label: "Japan (+81)", value: "+81" },
    { key: "JO", label: "Jordan (+962)", value: "+962" },
    { key: "KZ", label: "Kazakhstan (+7)", value: "+7" },
    { key: "KE", label: "Kenya (+254)", value: "+254" },
    { key: "KI", label: "Kiribati (+686)", value: "+686" },
    { key: "KP", label: "Korea, North (+850)", value: "+850" },
    { key: "KR", label: "Korea, South (+82)", value: "+82" },
    { key: "KW", label: "Kuwait (+965)", value: "+965" },
    { key: "KG", label: "Kyrgyzstan (+996)", value: "+996" },
    { key: "LA", label: "Laos (+856)", value: "+856" },
    { key: "LV", label: "Latvia (+371)", value: "+371" },
    { key: "LB", label: "Lebanon (+961)", value: "+961" },
    { key: "LS", label: "Lesotho (+266)", value: "+266" },
    { key: "LR", label: "Liberia (+231)", value: "+231" },
    { key: "LY", label: "Libya (+218)", value: "+218" },
    { key: "LI", label: "Liechtenstein (+423)", value: "+423" },
    { key: "LT", label: "Lithuania (+370)", value: "+370" },
    { key: "LU", label: "Luxembourg (+352)", value: "+352" },
    { key: "MG", label: "Madagascar (+261)", value: "+261" },
    { key: "MW", label: "Malawi (+265)", value: "+265" },
    { key: "MY", label: "Malaysia (+60)", value: "+60" },
    { key: "MV", label: "Maldives (+960)", value: "+960" },
    { key: "ML", label: "Mali (+223)", value: "+223" },
    { key: "MT", label: "Malta (+356)", value: "+356" },
    { key: "MH", label: "Marshall Islands (+692)", value: "+692" },
    { key: "MR", label: "Mauritania (+222)", value: "+222" },
    { key: "MU", label: "Mauritius (+230)", value: "+230" },
    { key: "MX", label: "Mexico (+52)", value: "+52" },
    { key: "FM", label: "Micronesia (+691)", value: "+691" },
    { key: "MD", label: "Moldova (+373)", value: "+373" },
    { key: "MC", label: "Monaco (+377)", value: "+377" },
    { key: "MN", label: "Mongolia (+976)", value: "+976" },
    { key: "ME", label: "Montenegro (+382)", value: "+382" },
    { key: "MA", label: "Morocco (+212)", value: "+212" },
    { key: "MZ", label: "Mozambique (+258)", value: "+258" },
    { key: "MM", label: "Myanmar (+95)", value: "+95" },
    { key: "NA", label: "Namibia (+264)", value: "+264" },
    { key: "NR", label: "Nauru (+674)", value: "+674" },
    { key: "NP", label: "Nepal (+977)", value: "+977" },
    { key: "NL", label: "Netherlands (+31)", value: "+31" },
    { key: "NZ", label: "New Zealand (+64)", value: "+64" },
    { key: "NI", label: "Nicaragua (+505)", value: "+505" },
    { key: "NE", label: "Niger (+227)", value: "+227" },
    { key: "NG", label: "Nigeria (+234)", value: "+234" },
    { key: "MK", label: "North Macedonia (+389)", value: "+389" },
    { key: "NO", label: "Norway (+47)", value: "+47" },
    { key: "OM", label: "Oman (+968)", value: "+968" },
    { key: "PK", label: "Pakistan (+92)", value: "+92" },
    { key: "PW", label: "Palau (+680)", value: "+680" },
    { key: "PS", label: "Palestine (+970)", value: "+970" },
    { key: "PA", label: "Panama (+507)", value: "+507" },
    { key: "PG", label: "Papua New Guinea (+675)", value: "+675" },
    { key: "PY", label: "Paraguay (+595)", value: "+595" },
    { key: "PE", label: "Peru (+51)", value: "+51" },
    { key: "PH", label: "Philippines (+63)", value: "+63" },
    { key: "PL", label: "Poland (+48)", value: "+48" },
    { key: "PT", label: "Portugal (+351)", value: "+351" },
    { key: "QA", label: "Qatar (+974)", value: "+974" },
    { key: "RO", label: "Romania (+40)", value: "+40" },
    { key: "RU", label: "Russia (+7)", value: "+7" },
    { key: "RW", label: "Rwanda (+250)", value: "+250" },
    { key: "KN", label: "Saint Kitts and Nevis (+1-869)", value: "+1-869" },
    { key: "LC", label: "Saint Lucia (+1-758)", value: "+1-758" },
    { key: "VC", label: "Saint Vincent and the Grenadines (+1-784)", value: "+1-784" },
    { key: "WS", label: "Samoa (+685)", value: "+685" },
    { key: "SM", label: "San Marino (+378)", value: "+378" },
    { key: "ST", label: "Sao Tome and Principe (+239)", value: "+239" },
    { key: "SA", label: "Saudi Arabia (+966)", value: "+966" },
    { key: "SN", label: "Senegal (+221)", value: "+221" },
    { key: "RS", label: "Serbia (+381)", value: "+381" },
    { key: "SC", label: "Seychelles (+248)", value: "+248" },
    { key: "SL", label: "Sierra Leone (+232)", value: "+232" },
    { key: "SG", label: "Singapore (+65)", value: "+65" },
    { key: "SK", label: "Slovakia (+421)", value: "+421" },
    { key: "SI", label: "Slovenia (+386)", value: "+386" },
    { key: "SB", label: "Solomon Islands (+677)", value: "+677" },
    { key: "SO", label: "Somalia (+252)", value: "+252" },
    { key: "ZA", label: "South Africa (+27)", value: "+27" },
    { key: "SS", label: "South Sudan (+211)", value: "+211" },
    { key: "ES", label: "Spain (+34)", value: "+34" },
    { key: "LK", label: "Sri Lanka (+94)", value: "+94" },
    { key: "SD", label: "Sudan (+249)", value: "+249" },
    { key: "SR", label: "Suriname (+597)", value: "+597" },
    { key: "SE", label: "Sweden (+46)", value: "+46" },
    { key: "CH", label: "Switzerland (+41)", value: "+41" },
    { key: "SY", label: "Syria (+963)", value: "+963" },
    { key: "TW", label: "Taiwan (+886)", value: "+886" },
    { key: "TJ", label: "Tajikistan (+992)", value: "+992" },
    { key: "TZ", label: "Tanzania (+255)", value: "+255" },
    { key: "TH", label: "Thailand (+66)", value: "+66" },
    { key: "TL", label: "Timor-Leste (+670)", value: "+670" },
    { key: "TG", label: "Togo (+228)", value: "+228" },
    { key: "TO", label: "Tonga (+676)", value: "+676" },
    { key: "TT", label: "Trinidad and Tobago (+1-868)", value: "+1-868" },
    { key: "TN", label: "Tunisia (+216)", value: "+216" },
    { key: "TR", label: "Turkey (+90)", value: "+90" },
    { key: "TM", label: "Turkmenistan (+993)", value: "+993" },
    { key: "TV", label: "Tuvalu (+688)", value: "+688" },
    { key: "UG", label: "Uganda (+256)", value: "+256" },
    { key: "UA", label: "Ukraine (+380)", value: "+380" },
    { key: "AE", label: "United Arab Emirates (+971)", value: "+971" },
    { key: "GB", label: "United Kingdom (+44)", value: "+44" },
    { key: "US", label: "United States (+1)", value: "+1" },
    { key: "UY", label: "Uruguay (+598)", value: "+598" },
    { key: "UZ", label: "Uzbekistan (+998)", value: "+998" },
    { key: "VU", label: "Vanuatu (+678)", value: "+678" },
    { key: "VE", label: "Venezuela (+58)", value: "+58" },
    { key: "VN", label: "Vietnam (+84)", value: "+84" },
    { key: "YE", label: "Yemen (+967)", value: "+967" },
    { key: "ZM", label: "Zambia (+260)", value: "+260" },
    { key: "ZW", label: "Zimbabwe (+263)", value: "+263" },
];